runtime: nodejs10

instance_class: F2

handlers:
  - url: /_nuxt
    static_dir: /frontend/.nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: frontend/static/\1
    upload: frontend/static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
