runtime: go111

instance_class: F1

automatic_scaling:
  max_instances: 1
  max_idle_instances: 1
  target_cpu_utilization: 0.9
  max_concurrent_requests: 50
  min_pending_latency: 1000ms
  max_pending_latency: automatic

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always

- url: /(blog|contact|about)/?$
  static_files: dist/\1.html
  upload: dist/.*\.html$
  secure: always

  # blog: html
- url: /blog/([0-9]{4})-([0-9]{2}-[0-9]{2})-([^\.]*)(\.html)?$
  static_files: dist/blog/\1-\2-\3.html
  upload: dist/blog/.*\.html$
  secure: always

  # blog: markdown
- url: /blog/([0-9]{4})-([0-9]{2}-[0-9]{2})-([^\.]*)\.md$
  static_files: posts/\1/\1-\2-\3.md
  upload: posts/.*\.md$
  secure: always

- url: /(app\.(js|css))$
  static_files: dist/\1
  upload: dist/(app\.(js|css))$
  secure: always

- url: /(favicon\.ico)$
  static_files: static/\1
  upload: static/favicon.ico$
  secure: always

- url: /img/(.*\.(gif|png|jpg|jpeg))$
  static_files: static/img/\1
  upload: static/img/.*\.(gif|png|jpg|jpeg)$
  secure: always

- url: /photos/(.*\.(gif|png|jpg|jpeg))$
  static_files: static/photos/\1
  upload: static/photos/.*\.(gif|png|jpg|jpeg)$
  secure: always

- url: /.*
  script: auto
  secure: always
