steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - helloworld
      - --source=./internal/functions/translate
      - --runtime go113
      - --trigger-http
timeout: "1600s"
