name: Auto-merge pull request updates

on:
  pull_request_review:
    types:
      - submitted

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Merge the branch
        if: github.event.review.state == 'approved'
        run: echo "approved"
