name: Auto-merge pull request updates

on:
  pull_request_review:
    types:
      - submitted

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Merge pull request
        if: github.event.review.state == 'approved'
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: 'main'
          github_token: ${{ github.token }}
